import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { exportAPI } from '@/lib/api';
import { getBucketClasses, formatDate, formatCurrency } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { 
    Printer, ArrowLeft, AlertTriangle, CheckCircle, HelpCircle, 
    Ban, Shield, FileText
} from 'lucide-react';

const bucketIcons = {
    'Prohibited': Ban,
    'High-risk': AlertTriangle,
    'Limited risk': HelpCircle,
    'Minimal risk': CheckCircle,
    'Needs clarification': HelpCircle
};

function Export() {
    const { id } = useParams();
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    
    useEffect(() => {
        const loadData = async () => {
            try {
                const exportData = await exportAPI.get(id);
                setData(exportData);
            } catch (err) {
                setError('Failed to load export data');
                console.error(err);
            } finally {
                setLoading(false);
            }
        };
        
        loadData();
    }, [id]);
    
    const handlePrint = () => {
        window.print();
    };
    
    if (loading) {
        return <ExportSkeleton />;
    }
    
    if (error || !data) {
        return (
            <div className="max-w-4xl mx-auto px-4 py-12">
                <Alert variant="destructive">
                    <AlertTriangle className="h-4 w-4" />
                    <AlertTitle>Error</AlertTitle>
                    <AlertDescription>{error || 'Export data not found'}</AlertDescription>
                </Alert>
            </div>
        );
    }
    
    const { project, assessment, disclaimer } = data;
    const classification = assessment.classification_json;
    const roadmap = assessment.roadmap_json;
    const BucketIcon = bucketIcons[classification?.bucket] || HelpCircle;
    
    // Get question labels for answers
    const questionLabels = {
        q1_company_role: 'Company Role',
        q2_deployment: 'Deployment',
        q3_domain: 'Domain',
        q4_decision_impact: 'Decision Impact',
        q5_data_types: 'Data Types',
        q6_biometric: 'Biometric Use',
        q7_safety_critical: 'Safety Critical',
        q8_human_oversight: 'Human Oversight',
        q9_behavior: 'Primary Behavior',
        q10_logging: 'Logging/Monitoring',
        q11_use_case: 'Use Case Description',
        q12_concern: 'Biggest Concern'
    };
    
    return (
        <div className="max-w-4xl mx-auto px-4 py-8 sm:py-12">
            {/* Print controls - hidden when printing */}
            <div className="no-print mb-8 flex items-center justify-between">
                <Button variant="ghost" asChild data-testid="back-to-results">
                    <Link to={`/results/${id}`}>
                        <ArrowLeft className="mr-2 h-4 w-4" />
                        Back to Results
                    </Link>
                </Button>
                <Button onClick={handlePrint} data-testid="print-btn">
                    <Printer className="mr-2 h-4 w-4" />
                    Print / Save as PDF
                </Button>
            </div>
            
            {/* Export Content */}
            <div className="print:shadow-none" data-testid="export-content">
                {/* Header */}
                <div className="flex items-center gap-4 mb-8">
                    <div className="h-12 w-12 rounded-lg bg-[#1E3A5F] flex items-center justify-center">
                        <span className="text-white font-bold text-lg">K</span>
                    </div>
                    <div>
                        <h1 className="font-heading text-2xl font-bold text-[#1E3A5F]">AI Act Risk Assessment</h1>
                        <p className="text-muted-foreground">Generated by KODEX Compliance</p>
                    </div>
                </div>
                
                {/* Project Info */}
                <Card className="mb-6">
                    <CardHeader>
                        <CardTitle>Project Information</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <dl className="grid sm:grid-cols-2 gap-4">
                            <div>
                                <dt className="text-sm text-muted-foreground">Project Name</dt>
                                <dd className="font-medium">{project.name}</dd>
                            </div>
                            {project.org_name && (
                                <div>
                                    <dt className="text-sm text-muted-foreground">Organization</dt>
                                    <dd className="font-medium">{project.org_name}</dd>
                                </div>
                            )}
                            <div>
                                <dt className="text-sm text-muted-foreground">Assessment Date</dt>
                                <dd className="font-medium">{formatDate(assessment.created_at)}</dd>
                            </div>
                            <div>
                                <dt className="text-sm text-muted-foreground">Version</dt>
                                <dd className="font-medium">{assessment.version}</dd>
                            </div>
                        </dl>
                    </CardContent>
                </Card>
                
                {/* Classification */}
                <Card className="mb-6">
                    <CardHeader>
                        <CardTitle>Risk Classification</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="flex items-center gap-4 mb-4">
                            <Badge className={`${getBucketClasses(classification?.bucket)} text-lg px-4 py-2 flex items-center gap-2`}>
                                <BucketIcon className="h-5 w-5" />
                                {classification?.bucket}
                            </Badge>
                            <span className="text-muted-foreground">
                                {classification?.confidence} confidence
                            </span>
                        </div>
                        <p className="text-foreground leading-relaxed">
                            {classification?.plain_language_summary}
                        </p>
                    </CardContent>
                </Card>
                
                {/* Answers Summary */}
                <Card className="mb-6 print-break-before">
                    <CardHeader>
                        <CardTitle>Assessment Answers</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <dl className="space-y-3">
                            {Object.entries(assessment.answers_json || {}).map(([key, value]) => {
                                if (!value) return null;
                                return (
                                    <div key={key} className="flex justify-between py-2 border-b last:border-0">
                                        <dt className="text-muted-foreground">{questionLabels[key] || key}</dt>
                                        <dd className="font-medium text-right max-w-xs">{value}</dd>
                                    </div>
                                );
                            })}
                        </dl>
                    </CardContent>
                </Card>
                
                {/* Transparency */}
                <Card className="mb-6">
                    <CardHeader>
                        <CardTitle>Transparency Details</CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        {/* Decisive Factors */}
                        {classification?.decisive_factors?.length > 0 && (
                            <div>
                                <h4 className="font-medium mb-2">Decisive Factors</h4>
                                <ul className="space-y-2">
                                    {classification.decisive_factors.map((factor, i) => (
                                        <li key={i} className="text-sm">
                                            <strong>{i + 1}.</strong> {factor.reason}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        )}
                        
                        <Separator />
                        
                        {/* Assumptions */}
                        {classification?.assumptions?.length > 0 && (
                            <div>
                                <h4 className="font-medium mb-2">Assumptions Made</h4>
                                <ul className="space-y-1">
                                    {classification.assumptions.map((assumption, i) => (
                                        <li key={i} className="text-sm flex items-start gap-2">
                                            <CheckCircle className="h-4 w-4 text-green-600 mt-0.5 flex-shrink-0" />
                                            {assumption}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        )}
                        
                        <Separator />
                        
                        {/* What Changes */}
                        {classification?.what_changes_outcome?.length > 0 && (
                            <div>
                                <h4 className="font-medium mb-2">What Would Change the Outcome</h4>
                                <ul className="space-y-1">
                                    {classification.what_changes_outcome.map((item, i) => (
                                        <li key={i} className="text-sm">• {item}</li>
                                    ))}
                                </ul>
                            </div>
                        )}
                    </CardContent>
                </Card>
                
                {/* Roadmap */}
                <Card className="mb-6 print-break-before">
                    <CardHeader>
                        <CardTitle>Compliance Roadmap</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="space-y-4">
                            {roadmap?.filter(t => t.is_top_5).map((task, i) => (
                                <div key={task.id} className="border-b pb-4 last:border-0">
                                    <div className="flex items-center gap-2 mb-2">
                                        <span className="h-6 w-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center text-xs font-bold">
                                            {i + 1}
                                        </span>
                                        <h4 className="font-medium">{task.title}</h4>
                                        <Badge variant="outline">{task.priority}</Badge>
                                    </div>
                                    <p className="text-sm text-muted-foreground mb-2">{task.why}</p>
                                    <div className="text-sm">
                                        <strong>Deliverable:</strong> {task.deliverable}
                                    </div>
                                </div>
                            ))}
                        </div>
                        
                        {roadmap?.length > 5 && (
                            <p className="text-sm text-muted-foreground mt-4 pt-4 border-t">
                                + {roadmap.length - 5} additional tasks in full roadmap
                            </p>
                        )}
                    </CardContent>
                </Card>
                
                {/* Estimator (if configured) */}
                {assessment.estimator_output_json && !assessment.estimator_output_json.error && (
                    <Card className="mb-6">
                        <CardHeader>
                            <CardTitle>Fine Exposure Simulation</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <div className="text-center p-4 bg-muted/50 rounded-lg mb-4">
                                <p className="text-sm text-muted-foreground mb-1">Theoretical Range</p>
                                <p className="text-2xl font-bold">
                                    {formatCurrency(assessment.estimator_output_json.min, assessment.estimator_output_json.currency)} — {formatCurrency(assessment.estimator_output_json.max, assessment.estimator_output_json.currency)}
                                </p>
                            </div>
                            <div>
                                <h4 className="text-sm font-medium mb-2">Assumptions:</h4>
                                <ul className="text-sm space-y-1">
                                    {assessment.estimator_output_json.assumptions?.map((a, i) => (
                                        <li key={i}>• {a}</li>
                                    ))}
                                </ul>
                            </div>
                        </CardContent>
                    </Card>
                )}
                
                {/* Disclaimer */}
                <Alert className="mb-6">
                    <AlertTriangle className="h-4 w-4" />
                    <AlertTitle>Important Notice</AlertTitle>
                    <AlertDescription>
                        {disclaimer}
                    </AlertDescription>
                </Alert>
                
                {/* Footer */}
                <div className="text-center text-sm text-muted-foreground pt-6 border-t">
                    <p>Generated by KODEX Compliance • {formatDate(new Date().toISOString())}</p>
                    <p className="mt-1">Educational information only — not legal advice</p>
                </div>
            </div>
        </div>
    );
}

function ExportSkeleton() {
    return (
        <div className="max-w-4xl mx-auto px-4 py-8 sm:py-12">
            <div className="flex justify-between mb-8">
                <Skeleton className="h-10 w-32" />
                <Skeleton className="h-10 w-40" />
            </div>
            <Skeleton className="h-24 w-full mb-6" />
            <Skeleton className="h-48 w-full mb-6" />
            <Skeleton className="h-64 w-full" />
        </div>
    );
}

export default Export;
